#! /usr/bin/env python

# System
import sys

# ROS
import rospy

# Smach state to test
from robot_smach_states import FindPersonInRoom


if __name__ == "__main__":
    if len(sys.argv) > 1:
        robot_name = sys.argv[1]
        area = sys.argv[2]
        name = sys.argv[3]
    else:
        print "Please provide robot name as argument."
        exit(1)

    if robot_name == "amigo":
        from robot_skills.amigo import Amigo as Robot
    elif robot_name == "sergio":
        from robot_skills.sergio import Sergio as Robot

    rospy.init_node('test_follow_operator')
    robot = Robot()
    sm = FindPersonInRoom(robot, area, name)
    sm.execute()
